spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/coupon
    username: root
    password: 1234

  data:
    redis:
      host: localhost
      port: 56379

kafka:
  host: localhost
  port: 9092